import { test,expect,type Page } from "@playwright/test";
const campaign={id:"00000000-0000-4000-8000-000000000020",name:"Sinh viên 5 Tốt · Năm học 2026–2027",academic_year:"2026-2027",start_date:"2026-01-01T00:00:00Z",end_date:"2027-12-31T00:00:00Z",is_active:true};
const profile={id:"00000000-0000-4000-8000-000000000010",full_name:"Nguyễn Minh Anh",email:"student@example.test",mssv:"3124000001",phone:"0900000000",role:"STUDENT",faculty_id:"faculty-a",class_name:"DCT1241",is_active:true,faculties:{name:"Khoa Công nghệ Thông tin",code:"CNTT"},majors:{name:"Kỹ thuật phần mềm"}};
const files=[{id:"f1",file_type:"DECLARATION_DOC",original_name:"ke-khai.docx",mime_type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",file_size_bytes:1024,revision:1,review_status:"PENDING",uploaded_at:"2026-09-15T00:00:00Z"}];
const application={id:"00000000-0000-4000-8000-000000000030",campaign_id:campaign.id,type:"INDIVIDUAL",status:"DRAFT",application_files:files,users:profile,updated_at:"2026-09-15T00:00:00Z",campaigns:campaign};
async function fixture(page:Page,role="STUDENT",apps:unknown[]=[application]){await page.route("**/api/v1/**",async route=>{const url=new URL(route.request().url());const path=url.pathname;let data:unknown=null;if(path.endsWith("/users/me"))data={...profile,role};else if(path.endsWith("/public/campaigns/active"))data=campaign;else if(path.endsWith("/public/faculties"))data=[{id:"faculty-a",name:"Khoa Công nghệ Thông tin",code:"CNTT",majors:[]}];else if(path.endsWith("/public/documents"))data=[];else if(path.endsWith("/campaigns"))data=[campaign];else if(path.includes("/statistics/summary"))data={totalSubmitted:12,pending:5,resubmitRequired:2,approved:4,rejected:1,faculties:[{name:"Khoa Công nghệ Thông tin",total:12,approved:4}]};else if(path.endsWith("/manager/applications"))data={items:[{...application,status:"SUBMITTED"}],total:1,pageSize:20};else if(path.endsWith("/applications"))data=apps;else if(path.endsWith("/admin/system/storage-health"))data={r2:{committedBytes:1230000,reservedBytes:0,hardLimitBytes:8589934592,percent:1,warning:false},database:{bytes:10000000,limitBytes:524288000}};else if(path.endsWith("/admin/users"))data={items:[profile],total:1};else if(path.endsWith("/admin/settings"))data={r2_hard_limit_bytes:8589934592,r2_warning_percent:75};else if(path.endsWith("/admin/audit"))data={items:[],total:0};else if(path.endsWith("/admin/documents")||path.endsWith("/export/jobs"))data=[];else if(path.endsWith("/auth/logout"))data={signedOut:true};else return route.continue();await route.fulfill({json:{data}});});}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy();}
test("student dashboard uses real response data and responsive layout",async({page})=>{await fixture(page);await page.setViewportSize({width:1440,height:1000});await page.goto("/dashboard");await expect(page.getByRole("heading",{name:"Xin chào, Anh!"})).toBeVisible();await expect(page.getByText("1/3",{exact:true})).toBeVisible();await noOverflow(page);await page.screenshot({path:"docs/screenshots/student-desktop.png",fullPage:true});});
test("student file upload is unavailable on phone; navigation remains usable",async({page})=>{await page.setViewportSize({width:390,height:844});await fixture(page);await page.goto("/application");await expect(page.getByText("Vui lòng dùng máy tính",{exact:false})).toBeVisible();await expect(page.getByRole("button",{name:"Chọn file"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Thay file"})).toHaveCount(0);await page.getByRole("button",{name:"Mở menu"}).click();await page.getByRole("link",{name:"Phản hồi xét duyệt"}).click();await expect(page.getByRole("heading",{name:"Phản hồi xét duyệt"})).toBeVisible();await noOverflow(page);await page.screenshot({path:"docs/screenshots/student-mobile.png",fullPage:true});});
test("missing file blocks submission and network error is actionable",async({page})=>{await fixture(page);await page.goto("/application");await expect(page.getByRole("button",{name:"Nộp hồ sơ",exact:true})).toBeDisabled();await page.route("**/api/v1/applications",r=>r.fulfill({status:503,json:{error:{message:"Không thể kết nối thử nghiệm."}}}));await page.reload();await expect(page.getByRole("alert").filter({hasText:"Không thể kết nối thử nghiệm."})).toBeVisible();await expect(page.getByRole("button",{name:"Thử lại"})).toBeVisible();});
test("public library does not expose student template",async({page})=>{await fixture(page);await page.route("**/api/v1/users/me",r=>r.fulfill({status:401,json:{error:{message:"Chưa đăng nhập"}}}));await page.goto("/documents");await expect(page.getByText("Biểu mẫu dành cho sinh viên",{exact:true})).toBeVisible();await expect(page.locator('a[href="/api/v1/documents/individual-template/download"]')).toHaveCount(0);await expect(page.locator('a[href="/api/v1/documents/criteria/download"]')).toBeVisible();});
test("all manager and admin navigation routes render",async({page})=>{await fixture(page,"SCHOOL_PRESIDENT");for(const path of ["/manager","/manager/applications","/manager/statistics","/manager/export","/manager/campaigns","/manager/settings","/manager/profile"]){await page.goto(path);await expect(page.locator("h1")).toBeVisible();await expect(page.getByText("This page could not be found.")).toHaveCount(0);}await page.goto("/manager");await expect(page.getByText("Nguyễn Minh Anh").first()).toBeVisible();await page.screenshot({path:"docs/screenshots/manager-desktop.png",fullPage:true});await fixture(page,"SUPER_ADMIN");for(const path of ["/admin","/admin/users","/admin/campaigns","/admin/documents","/admin/settings","/admin/audit","/admin/security"]){await page.goto(path);await expect(page.locator("h1")).toBeVisible();await expect(page.getByText("This page could not be found.")).toHaveCount(0);}await page.goto("/admin");await page.screenshot({path:"docs/screenshots/admin-desktop.png",fullPage:true});});
test("landing remains readable on mobile and desktop",async({page})=>{await fixture(page);await page.goto("/");await expect(page.getByRole("heading",{level:1})).toBeVisible();await page.screenshot({path:"docs/screenshots/landing-desktop.png",fullPage:true});await page.setViewportSize({width:390,height:844});await noOverflow(page);await page.screenshot({path:"docs/screenshots/landing-mobile.png",fullPage:true});});
